import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { ProductProvider } from "./context/ProductContext"
import { Manrope } from "next/font/google";

import { CartProvider } from "./context/CardContext";

const manrope = Manrope({ subsets: ["latin"], weight: ["400","500","700"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={manrope.className}
      >
         <ProductProvider>
      <CartProvider>
        <Nav />  
        {children}
      </CartProvider>
    </ProductProvider>
    
    <Footer/>
      </body>
    </html>
  );
}
